"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-n8n^(k#j0(e!wm_d43i-^(ac5m+-7$xxsqvy@@0dy@z#igqqcc"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'api',
    'user',
    'social_django',

]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'social_django.middleware.SocialAuthExceptionMiddleware',

]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTHENTICATION_BACKENDS = (
    'social_core.backends.keycloak.KeycloakOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

# KEYCLOAK_SERVER_URL = 'http://localhost:8080/auth/'  
# KEYCLOAK_REALM = 'master'  
# KEYCLOAK_REDIRECT_URI = 'http://localhost:8000/oauth2/callback/'

LOGIN_URL = '/auth/login/keycloak/'  
LOGIN_REDIRECT_URL = '/'             
LOGOUT_REDIRECT_URL = '/'            

SOCIAL_AUTH_KEYCLOAK_KEY = 'django'  
SOCIAL_AUTH_KEYCLOAK_SECRET = 'Uz0UOSYUo5ky3nMEAR89rsHROTUsferN'
SOCIAL_AUTH_KEYCLOAK_REALM = 'django-realm'
SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY = (
    "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0oPlkQMqlymbfllbUlJGuD9E0BjS/NAmVCPjWMlxn6eGDJLuggTxC6/dboaM1sIdIA1Fz3HNV2U+TG9U//3CD5Q2KMcXqR7FROiSRk/zPOUd9D5ZbEkYh5hNhNv8yXpFKtuyPtIJ1K54a7CmrDfqRHONtAAj4Il54GH9w9tRHaoB5c6mTzChY8pZzZihKjEoJXch8PO2yM9A9My1/Xdd5cs/RS9cPYYTODH2GKyzqjyb0ZN3ep2ddzQ+mI2D/DurqRYNS/qTlGtjvXZ3nhj8QnhZDk9UtXERHdPtzU4+76UcVAG1ZMnAFkaBZQLhPikyh3fz6Xxbql7MEdLKdRj4ywIDAQAB"
)

SOCIAL_AUTH_KEYCLOAK_IGNORE_DEFAULT_SCOPE = True
SOCIAL_AUTH_KEYCLOAK_EXTRA_DATA = ['id_token']
SOCIAL_AUTH_KEYCLOAK_SKIP_JWT_VERIFICATION = True

SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL = 'http://localhost:8081/realms/django-realm/protocol/openid-connect/auth'
SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL = 'http://localhost:8081/realms/django-realm/protocol/openid-connect/token'
SOCIAL_AUTH_KEYCLOAK_USER_INFO_URL = 'http://localhost:8081/realms/django-realm/protocol/openid-connect/userinfo'

KEYCLOAK_SERVER_URL = 'http://localhost:8081/'
KEYCLOAK_REALM = 'master'
KEYCLOAK_ADMIN_USERNAME = 'admin'
KEYCLOAK_ADMIN_PASSWORD = 'admin'
KEYCLOAK_CLIENT_ID = 'admin-cli'

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
